version: '3.8'
services:
  odoo:
    image: odoo:15
    depends_on:
      - psql
    ports:
      - "8069:8069"
    volumes:
      - odoo-data:/var/lib/odoo
      - ./config:/etc/odoo
      - ./x-apps:/mnt/extra-addons
    environment:
      - HOST=psql
      - PORT=5432
      - USER=odoo15
      - PASSWORD_FILE=/run/secrets/postgresql_password
    secrets:
      - postgresql_password
  psql:
    image: postgres:14
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_PASSWORD_FILE=/run/secrets/postgresql_password
      - POSTGRES_USER=odoo15
      - PGDATA=/var/lib/postgresql/data/pgdata
    volumes:
      - psql-data:/var/lib/postgresql/data/pgdata
    secrets:
      - postgresql_password
volumes:
  odoo-data:
  psql-data:

secrets:
  postgresql_password:
    file: odoo_db.password

